# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adf9c3864bee999598527eef0f70bb9f949060e4ba6591c0aa7defe61f12bd1586599f844ac9f1aee3f7fee40f5753a7f69a3ace56092999294401cabc21dbd3

test:
  secret_key_base: b8ea7551fea5fb68d15ac38bc8475116887d38fe2de5e5bc13e9d684227641d22e03356c4f50d71c4dd833a8a1243e2e517a9fb01b0c83c810ad5c6c9f3b7dd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
